[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[dev]
  command = "vite"
  port = 5173
  functionsPort = 8888

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"